//partes bloqueadas de sites
var blocked_parts = [
    "/ad/",
    "/pagead/",
    "jsbin/www-pagead-id-",
    "/get_midroll_",
    "/api/stats",
    "/ptracking",
    "/ads",
    "/yt/advertise",
    "advertise.css",
    "adsense",
    "/js/www-advertise",
    "advertise",
    "/_get_ads",
    "adunit",
    "/ad",
    "adservice.",
    "ads.",
    "adPlacements",
    "playerAds",
];